name: PHP CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl, pdo_mysql
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      if: hashFiles('composer.json') != ''
      run: composer validate --strict

    - name: Install dependencies
      if: hashFiles('composer.json') != ''
      run: composer install --prefer-dist --no-progress

    - name: Lint PHP files
      run: find . -name "*.php" -exec php -l {} \; | (! grep -v "No syntax errors detected")
